### ISSUE TITLE
Case sensitivity issue with ArchEthic Wallet on Android

### ISSUE THREAD

**Issue by ghost** [redDwarf03/archethic_mobile_wallet#213]
### Describe the problem you discovered

If you want to claim test tokens via the faucet, you must copy your UCO address. To do this we press RECEIVE which gives us the possibility to copy our by making a long press or to copy it after pressing SHARE. 
When you do a long press on the QR code, the UCO address is copied but in lowercase and when you use the SHARE function, the UCO address is in uppercase. 
Once on the blockhain explorer, in the faucet tab by pasting the address in uppercase, you receive a WARNING "Malformation address" while by pasting the one obtained by long pressing the QR code (in lowercase) , there is no hassle to claim the faucet. Either it is the SHARE function which does not provide the correct address.

UPPERCASE ADDRESS
![photo_2022-07-21_22-39-45](https://user-images.githubusercontent.com/109767374/180319908-f9d311c1-9281-4267-ac16-f09ce5003f3d.jpg)

LOWERCASE ADDRES
![photo_2022-07-21_22-44-20](https://user-images.githubusercontent.com/109767374/180320806-70a8fa1c-d092-488c-b3ef-efe8456bf6ff.jpg)

### Describe the solution you'd like

Make the explorer case insensitive or make the SHARE function generate the same address as the one generated by long pressing the QR code.

**Comment by redDwarf03** [comment]
Hello
thank you for your feedback. It's not a problem of case sensitivity. the problem comes from the share feature which add a blank character at the end of the address when you want to copy it.
This pb is known and has been declared in january to the creator of the Share plugin (https://github.com/fluttercommunity/plus_plugins/issues/701)
i create an issue on the faucet to trim the blank at the end of address to help users:
https://github.com/archethic-foundation/archethic-node/issues/468

**Comment by ghost** [comment]
Thank all of you for your feedback

**Comment by redDwarf03** [comment]
fixed in the faucet in node explorer

**Comment by ghost** [comment]
Hello. Good to know that this issue have already be solved.

Le ven. 22 juil. 2022 à 07:50, redDwarf03 ***@***.***> a
écrit :
