### ISSUE TITLE
Consideration of the needs of color blind people

### ISSUE THREAD

**Issue by redDwarf03** [redDwarf03/archethic_mobile_wallet#558]
### Is your feature request related to a problem?
See the good practices on this subject and define the action plan in this issue

**Comment by gdaguin** [comment]
Since Flutter 2.10, it is possible to use material 3 components instead of material 2 ones.
Thus, we can let material 3 manage the accessibility of the application itself : https://m3.material.io/styles/color/the-color-system/accessibility
That's a massive work to do if you want to go there, but it is going to simplify a lot of things though.

**Comment by redDwarf03** [comment]
Yes. we used material 3 in new flutter projects, https://github.com/archethic-foundation/aeweb
But in the wallet, we have too many tasks to prioritize for the moment material 3
I put this issue to stand by status
Thank you

**Comment by redDwarf03** [comment]
Material3 is used in the wallet
The brand was defined with website works
I close this issue for the moment
